=== gcoronelc/SISTUNI-JWS-002/Tema04/EjemplosXML/src/xml/documento.dtd
<!-- documento.dtd -->
<!ELEMENT documento (titulo, autor, seccion+)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT seccion (tema,parrafo+)>
<!ELEMENT tema (#PCDATA)>
<!ELEMENT parrafo (#PCDATA)>

=== gcoronelc/SISTUNI-JWS-002/Tema04/EjemplosXML/src/xml/documento.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- documento.xml -->
<!DOCTYPE documento SYSTEM "documento.dtd">
<documento>
  <titulo>Fundamentos de XML</titulo>
  <autor>Gustavo Coronel</autor>
  <seccion>
    <tema>Introducci√≥n</tema>
    <parrafo>Parrafo 1</parrafo>
    <parrafo>Parrafo 2</parrafo>
  </seccion>
  <seccion>
    <tema>XML Validos</tema>
    <parrafo>Parrafo 1</parrafo>
    <parrafo>Parrafo 2</parrafo>
  </seccion>
</documento>
