=== gcoronelc/SISTUNI-JWS-002/Tema04/EjemplosXML/src/xml/ejm06.dtd
<!-- ejm06.dtd -->
<!ELEMENT direccion (nombre, calle, ciudad, estado, codigo-postal)>
<!ELEMENT nombre (titulo, nombres, apellidos)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT nombres (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT estado (#PCDATA)>
<!ELEMENT codigo-postal (#PCDATA)>

=== gcoronelc/SISTUNI-JWS-002/Tema04/EjemplosXML/src/xml/ejm06.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ejm06.xml -->
<!DOCTYPE direccion SYSTEM "ejm06.dtd">
<direccion>
  <nombre>
    <titulo>Mrs.</titulo>
    <nombres>Mary</nombres>
    <apellidos>McGoon</apellidos>
  </nombre>
  <calle>1401 Main Street</calle>
  <ciudad>Anytown</ciudad>
  <estado>NC</estado>
  <codigo-postal>34829</codigo-postal>
</direccion>
